# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2025-12-05 09:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('credit', '0002_auto_20251205_1218'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loanrequest',
            name='paid_amount',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=12, null=True),
        ),
    ]
