# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2025-12-05 13:29
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('credit', '0003_auto_20251205_1231'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loanrequest',
            name='member',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='member_loan_request', to='coop.CooperativeMember'),
        ),
    ]
