# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2023-09-21 23:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coop', '0034_cooperativemember_bee_hives'),
    ]

    operations = [
        migrations.AddField(
            model_name='cooperativemember',
            name='consent_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='cooperativemember',
            name='consumer_device_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='cooperativemember',
            name='cpk_rid',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='cooperativemember',
            name='passcode',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='cooperativemember',
            name='chia_trees',
            field=models.PositiveIntegerField(blank=True, default=0, null=True, verbose_name='Chia Trees'),
        ),
    ]
