# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2023-10-19 13:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coop', '0035_auto_20230922_0215'),
    ]

    operations = [
        migrations.AddField(
            model_name='cooperativemember',
            name='card_number',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='cooperativemember',
            name='community_pass_biometric_consent',
            field=models.BooleanField(default=1),
        ),
        migrations.AddField(
            model_name='cooperativemember',
            name='community_pass_partner_pii',
            field=models.BooleanField(default=1),
        ),
        migrations.AddField(
            model_name='cooperativemember',
            name='community_pass_privacy_policy_consent',
            field=models.BooleanField(default=1),
        ),
    ]
