# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2023-11-23 12:12
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('coop', '0036_auto_20231019_1624'),
    ]

    operations = [
        migrations.AlterField(
            model_name='memberorder',
            name='cooperative',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='coop.Cooperative'),
        ),
    ]
