# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2023-11-24 12:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coop', '0037_auto_20231123_1512'),
    ]

    operations = [
        migrations.AddField(
            model_name='cooperativemember',
            name='account_balance',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=32),
        ),
    ]
