# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2023-11-29 16:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coop', '0038_cooperativemember_account_balance'),
    ]

    operations = [
        migrations.AddField(
            model_name='cooperativemember',
            name='has_wallet',
            field=models.BooleanField(default=False),
        ),
    ]
