# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2023-11-30 02:06
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('coop', '0039_cooperativemember_has_wallet'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cooperativemember',
            old_name='has_wallet',
            new_name='create_wallet',
        ),
    ]
