# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2024-01-31 16:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coop', '0040_auto_20231130_0506'),
    ]

    operations = [
        migrations.AddField(
            model_name='cooperative',
            name='sent_to_tiv',
            field=models.BooleanField(default=0),
        ),
    ]
