# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2024-02-01 08:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coop', '0041_cooperative_sent_to_tiv'),
    ]

    operations = [
        migrations.AddField(
            model_name='cooperativemember',
            name='sent_to_tiv',
            field=models.BooleanField(default=0),
        ),
    ]
