# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2024-02-02 06:49
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('coop', '0042_cooperativemember_sent_to_tiv'),
    ]

    operations = [
        migrations.CreateModel(
            name='OKOMemberPolicy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('policyId', models.CharField(blank=True, max_length=12, null=True, unique=True, verbose_name='Farm Name')),
                ('amount_due', models.DecimalField(decimal_places=2, max_digits=9)),
                ('amount_paid', models.DecimalField(decimal_places=2, default=0, max_digits=9)),
                ('claim_status', models.PositiveIntegerField(default=1)),
                ('end_date', models.DateTimeField(blank=True, null=True)),
                ('create_date', models.DateTimeField(auto_now_add=True)),
                ('update_date', models.DateTimeField(auto_now=True)),
                ('cooperative_member', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='coop.CooperativeMember')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'oko_policy',
            },
        ),
        migrations.CreateModel(
            name='Season',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('crop', models.CharField(blank=True, max_length=120, null=True, unique=True, verbose_name='Crop')),
                ('Year', models.CharField(blank=True, max_length=120, null=True, unique=True, verbose_name='Year')),
                ('session_id', models.CharField(blank=True, max_length=120, null=True, unique=True, verbose_name='Session ID')),
                ('create_date', models.DateTimeField(auto_now_add=True)),
                ('update_date', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
