# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2024-02-02 11:53
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('coop', '0043_okomemberpolicy_season'),
    ]

    operations = [
        migrations.AddField(
            model_name='okomemberpolicy',
            name='season',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='coop.Season'),
        ),
        migrations.AlterField(
            model_name='okomemberpolicy',
            name='policyId',
            field=models.CharField(blank=True, max_length=12, null=True, unique=True),
        ),
    ]
