# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2024-03-07 00:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coop', '0044_auto_20240202_1453'),
    ]

    operations = [
        migrations.CreateModel(
            name='OKOLocation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('region', models.CharField(max_length=12)),
                ('district', models.CharField(max_length=12)),
                ('sub_county', models.CharField(max_length=12)),
            ],
            options={
                'db_table': 'oko_location',
            },
        ),
    ]
