# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2024-03-07 01:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coop', '0045_okolocation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='okolocation',
            name='district',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='okolocation',
            name='region',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='okolocation',
            name='sub_county',
            field=models.CharField(max_length=255),
        ),
    ]
