# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2024-03-07 05:49
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('coop', '0046_auto_20240307_0428'),
    ]

    operations = [
        migrations.AddField(
            model_name='okolocation',
            name='create_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='okolocation',
            name='update_date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
