# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2024-03-20 02:37
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('coop', '0048_auto_20240307_1152'),
    ]

    operations = [
        migrations.CreateModel(
            name='FlexiPayTransaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference', models.CharField(blank=True, max_length=255, null=True, unique=True)),
                ('request', models.TextField(blank=True, null=True)),
                ('response', models.TextField(blank=True, null=True)),
                ('status', models.CharField(blank=True, max_length=16, null=True)),
                ('create_date', models.DateTimeField(auto_now_add=True)),
                ('update_date', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'flexypay',
            },
        ),
        migrations.AddField(
            model_name='cooperativemember',
            name='has_flexipay',
            field=models.BooleanField(default=0),
        ),
        migrations.AddField(
            model_name='flexipaytransaction',
            name='cooperative_member',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='coop.CooperativeMember'),
        ),
    ]
