# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2025-12-05 09:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coop', '0049_auto_20240320_0537'),
    ]

    operations = [
        migrations.AddField(
            model_name='collection',
            name='repay_loan',
            field=models.BooleanField(default=False),
        ),
    ]
