# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2025-12-05 13:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coop', '0050_collection_repay_loan'),
    ]

    operations = [
        migrations.AlterField(
            model_name='farmergroup',
            name='savings_balance',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=32, null=True),
        ),
    ]
