# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2026-03-16 01:06
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('coop', '0052_clan'),
    ]

    operations = [
        migrations.AddField(
            model_name='cooperativemember',
            name='clan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='coop.Clan'),
        ),
    ]
