# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2026-03-16 07:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coop', '0053_cooperativemember_clan'),
    ]

    operations = [
        migrations.AddField(
            model_name='clan',
            name='totem',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
