# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2023-11-14 07:29
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('userprofile', '0008_device_devicelocation'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='in_charge',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='person_incharge', to=settings.AUTH_USER_MODEL),
        ),
    ]
