# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2023-11-22 15:33
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('conf', '0003_auto_20231122_1833'),
        ('userprofile', '0009_device_in_charge'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='county',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='conf.County'),
        ),
        migrations.AddField(
            model_name='profile',
            name='district_incharge',
            field=models.ManyToManyField(blank=True, null=True, to='conf.District'),
        ),
        migrations.AddField(
            model_name='profile',
            name='gps_coodinates',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='parish',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='conf.Parish'),
        ),
        migrations.AddField(
            model_name='profile',
            name='profile_photo',
            field=models.ImageField(null=True, upload_to='user/'),
        ),
        migrations.AddField(
            model_name='profile',
            name='sub_county',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='conf.SubCounty'),
        ),
        migrations.AddField(
            model_name='profile',
            name='village',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.RemoveField(
            model_name='profile',
            name='district',
        ),
        migrations.AddField(
            model_name='profile',
            name='district',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='profile_district', to='conf.District'),
        ),
    ]
