# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2023-11-26 01:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0012_profile_is_supervisor'),
    ]

    operations = [
        migrations.AddField(
            model_name='devicelocation',
            name='device_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
