# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2023-11-28 14:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0013_devicelocation_device_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='devicelocation',
            name='androidId',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
