# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2023-12-09 08:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0014_devicelocation_androidid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='device_id',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
