# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2025-10-06 07:25
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0015_auto_20231209_1158'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='otp_secret',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name='accesslevelgroup',
            name='access_level',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='group_links', to='userprofile.AccessLevel'),
        ),
        migrations.AlterField(
            model_name='accesslevelgroup',
            name='group',
            field=models.ManyToManyField(related_name='access_levels', to='auth.Group'),
        ),
    ]
