# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2025-12-04 07:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0016_auto_20251006_1025'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='enable_mfa',
            field=models.BooleanField(default=False),
        ),
    ]
